// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using EntityFrameworkCore.Jet.Metadata;
using EntityFrameworkCore.LibRed.Storage.Internal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Scaffolding;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TestNamespace;

public partial class FunctionParameterTypeMappingContextModel
{
    private FunctionParameterTypeMappingContextModel()
        : base(skipDetectChanges: true, modelId: new Guid("00000000-0000-0000-0000-000000000000"), entityTypeCount: 0)
    {
    }

    partial void Initialize()
    {
        var functions = new Dictionary<string, IDbFunction>();
        var getSqlFragmentStatic = new RuntimeDbFunction(
            "Microsoft.EntityFrameworkCore.Scaffolding.CompiledModelRelationalTestBase+FunctionParameterTypeMappingContext.GetSqlFragmentStatic(string)",
            this,
            typeof(string),
            "GetSqlFragmentStatic",
            storeType: "varchar(255)",
            methodInfo: typeof(CompiledModelRelationalTestBase.FunctionParameterTypeMappingContext).GetMethod(
                "GetSqlFragmentStatic",
                BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly,
                null,
                new Type[] { typeof(string) },
                null),
            scalar: true,
            nullable: true);

        var param = getSqlFragmentStatic.AddParameter(
            "param",
            typeof(string),
            false,
            "varchar");
        param.TypeMapping = StringTypeMapping.Default.Clone(
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "varchar",
                dbType: System.Data.DbType.AnsiString));

        getSqlFragmentStatic.TypeMapping = LibRedStringTypeMapping.Default.Clone(
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "varchar(255)",
                size: 255));
        functions["Microsoft.EntityFrameworkCore.Scaffolding.CompiledModelRelationalTestBase+FunctionParameterTypeMappingContext.GetSqlFragmentStatic(string)"] = getSqlFragmentStatic;

        AddAnnotation("Relational:DbFunctions", functions);
        AddAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);
        AddAnnotation("Relational:MaxIdentifierLength", 64);
        AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
    }

    private IRelationalModel CreateRelationalModel()
    {
        var relationalModel = new RelationalModel(this);
        var getSqlFragmentStatic = (IRuntimeDbFunction)this.FindDbFunction("Microsoft.EntityFrameworkCore.Scaffolding.CompiledModelRelationalTestBase+FunctionParameterTypeMappingContext.GetSqlFragmentStatic(string)")!;
        var getSqlFragmentStaticFunction = new StoreFunction(getSqlFragmentStatic, relationalModel);
        var paramFunctionParameter = getSqlFragmentStaticFunction.FindParameter("param")!;
        relationalModel.Functions.Add(
            ("GetSqlFragmentStatic", null, new[] { "varchar" }),
            getSqlFragmentStaticFunction);
        return relationalModel.MakeReadOnly();
    }
}
