//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Data.Jet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Data.Jet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataTable&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;CheckConstraints&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;CheckConstraints&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///                &lt;xs:e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinition_CheckConstraints {
            get {
                return ResourceManager.GetString("StoreSchemaDefinition_CheckConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataTable&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;ConstraintColumns&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;ConstraintColumns&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///                &lt;xs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinition_ConstraintColumns {
            get {
                return ResourceManager.GetString("StoreSchemaDefinition_ConstraintColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataTable&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;Constraints&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;Constraints&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///                &lt;xs:element nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinition_Constraints {
            get {
                return ResourceManager.GetString("StoreSchemaDefinition_Constraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataTable&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;ForeignKeyConstraints&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;ForeignKeyConstraints&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinition_ForeignKeyConstraints {
            get {
                return ResourceManager.GetString("StoreSchemaDefinition_ForeignKeyConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataTable&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;ForeignKeys&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;ForeignKeys&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///                &lt;xs:element nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinition_ForeignKeys {
            get {
                return ResourceManager.GetString("StoreSchemaDefinition_ForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataTable&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;FunctionParameters&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;FunctionParameters&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///                &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinition_FunctionParameters {
            get {
                return ResourceManager.GetString("StoreSchemaDefinition_FunctionParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataTable&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;FunctionReturnTableColumns&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;FunctionReturnTableColumns&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinition_FunctionReturnTableColumns {
            get {
                return ResourceManager.GetString("StoreSchemaDefinition_FunctionReturnTableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataTable&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;Functions&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;Functions&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///                &lt;xs:element name=&quot;I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinition_Functions {
            get {
                return ResourceManager.GetString("StoreSchemaDefinition_Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataTable&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;IndexColumns&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;IndexColumns&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///                &lt;xs:element n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinition_IndexColumns {
            get {
                return ResourceManager.GetString("StoreSchemaDefinition_IndexColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataTable&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;Indexes&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;Indexes&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///                &lt;xs:element name=&quot;Id&quot; t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinition_Indexes {
            get {
                return ResourceManager.GetString("StoreSchemaDefinition_Indexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataTable&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;ProcedureParameters&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;ProcedureParameters&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinition_ProcedureParameters {
            get {
                return ResourceManager.GetString("StoreSchemaDefinition_ProcedureParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataTable&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;Procedures&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;Procedures&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///                &lt;xs:element name= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinition_Procedures {
            get {
                return ResourceManager.GetString("StoreSchemaDefinition_Procedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataTable&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;TableColumns&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;TableColumns&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///                &lt;xs:element n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinition_TableColumns {
            get {
                return ResourceManager.GetString("StoreSchemaDefinition_TableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataTable&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;Tables&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;Tables&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///                &lt;xs:element name=&quot;Id&quot; typ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinition_Tables {
            get {
                return ResourceManager.GetString("StoreSchemaDefinition_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataTable&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;ViewColumns&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;ViewColumns&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///                &lt;xs:element nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinition_ViewColumns {
            get {
                return ResourceManager.GetString("StoreSchemaDefinition_ViewColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataTable&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;ViewConstraintColumns&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;ViewConstraintColumns&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinition_ViewConstraintColumns {
            get {
                return ResourceManager.GetString("StoreSchemaDefinition_ViewConstraintColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataTable&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;ViewConstraints&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;ViewConstraints&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///                &lt;xs:ele [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinition_ViewConstraints {
            get {
                return ResourceManager.GetString("StoreSchemaDefinition_ViewConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataTable&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;ViewForeignKeys&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;ViewForeignKeys&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///                &lt;xs:ele [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinition_ViewForeignKeys {
            get {
                return ResourceManager.GetString("StoreSchemaDefinition_ViewForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataTable&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;Views&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;Views&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///                &lt;xs:element name=&quot;Id&quot; type= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinition_Views {
            get {
                return ResourceManager.GetString("StoreSchemaDefinition_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	[#TableColumns].[Ordinal] AS [C1], 
        ///	[#Tables].[CatalogName] AS [CatalogName], 
        ///	[#Tables].[SchemaName] AS [SchemaName], 
        ///	[#Tables].[Name] AS [Name], 
        ///	[#TableColumns].[Name] AS [C2], 
        ///	[#TableColumns].[IsNullable] AS [C3], 
        ///	[#TableColumns].[TypeName] AS [C4], 
        ///	[#TableColumns].[MaxLength] AS [C5], 
        ///	[#TableColumns].[Precision] AS [C6], 
        ///	[#TableColumns].[DateTimePrecision] AS [C7], 
        ///	[#TableColumns].[Scale] AS [C8], 
        ///	[#TableColumns].[IsIdentity] AS [C9], 
        ///	[#TableColumns].[IsStoreG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinitionRetrieve_QueryHack1 {
            get {
                return ResourceManager.GetString("StoreSchemaDefinitionRetrieve_QueryHack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	[#ViewColumns].[Ordinal] AS [C1], 
        ///	[#Views].[CatalogName] AS [CatalogName], 
        ///	[#Views].[SchemaName] AS [SchemaName], 
        ///	[#Views].[Name] AS [Name], 
        ///	[#ViewColumns].[Name] AS [C2], 
        ///	[#ViewColumns].[IsNullable] AS [C3], 
        ///	[#ViewColumns].[TypeName] AS [C4], 
        ///	[#ViewColumns].[MaxLength] AS [C5], 
        ///	[#ViewColumns].[Precision] AS [C6], 
        ///	[#ViewColumns].[DateTimePrecision] AS [C7], 
        ///	[#ViewColumns].[Scale] AS [C8], 
        ///	[#ViewColumns].[IsIdentity] AS [C9], 
        ///	[#ViewColumns].[IsStoreGenerated] AS  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreSchemaDefinitionRetrieve_QueryHack2 {
            get {
                return ResourceManager.GetString("StoreSchemaDefinitionRetrieve_QueryHack2", resourceCulture);
            }
        }
    }
}
