namespace LibRed.Storage;

/// <summary>
/// The General v0 weights for the Unicode blocks beyond Latin-1 and Latin Extended-A — Greek, Cyrillic,
/// Hebrew, Arabic, the Latin extensions, punctuation, currency and the fullwidth forms. Consulted by
/// <see cref="JetTextCollation"/> only after its own tables, so nothing here can change a weight that was
/// already verified by hand.
/// </summary>
/// <remarks>
/// Every byte was measured from ACE and is regenerated by <c>TailoringGeneratorProbeTest</c>: it has ACE
/// encode each character in a block, reads the stored index keys back, and prints these strings. They are
/// data, not something to hand-edit — around 1,500 entries as a dictionary literal would be neither readable
/// nor reviewable, and transcribing hex by hand is how a wrong byte gets in unnoticed.
/// <para>
/// Each string is <c>start|</c> then one token per consecutive code point:
/// <list type="bullet">
/// <item><c>-</c> — <b>ignorable</b>: ACE stores no weight at all for it, so it contributes nothing to a key,
/// not even a secondary slot. Romanian's comma-below <c>ș</c>/<c>ț</c> are in this class, which is why they
/// keep "General weights" — General has none for them.</item>
/// <item><c>?</c> — no data: ACE would not store the character, so the encoder refuses it rather than
/// guessing.</item>
/// <item><c>HEX</c> — the primary weight bytes, with the default secondary.</item>
/// <item><c>HEX,SS</c> — primary bytes and a secondary of its own.</item>
/// </list>
/// Note the non-Latin scripts nearly all live on the two-byte <c>0x79</c> page, the same page the locale
/// tailorings use for letters that sort after Z.
/// </para>
/// </remarks>
internal static class JetTextCollationBlocks
{
    /// <summary>The weight for a character, or null when it is ignorable. False when the block tables have
    /// nothing for it, in which case the caller must refuse the value rather than emit a guess.</summary>
    public static bool TryGet(char c, out TailoredWeight? weight) => Entries.Value.TryGetValue(c, out weight);

    // Lazy, because a static field initialiser would run before Tables below is assigned.
    private static readonly Lazy<Dictionary<char, TailoredWeight?>> Entries = new(Parse);

    private static Dictionary<char, TailoredWeight?> Parse()
    {
        var entries = new Dictionary<char, TailoredWeight?>();
        foreach (string table in Tables)
        {
            int bar = table.IndexOf('|');
            int start = Convert.ToInt32(table[..bar], 16);
            foreach (string token in table[(bar + 1)..].Split(' ', StringSplitOptions.RemoveEmptyEntries))
            {
                char c = (char)start++;
                if (token == "?") continue;
                if (token == "-") { entries[c] = null; continue; }
                int comma = token.IndexOf(',');
                byte[] primaries = Convert.FromHexString(comma < 0 ? token : token[..comma]);
                byte secondary = comma < 0 ? (byte)0x02 : Convert.ToByte(token[(comma + 1)..], 16);
                entries[c] = new TailoredWeight(primaries, secondary);
            }
        }
        return entries;
    }

    private static readonly string[] Tables =
    [
        // Latin Extended-B — U+0180..U+024F
        "0180|" +
        "4C,1E 4C,43 4C,68 4C,68 4C,87 4C,87 4D,7D 4D,43 4D,43 5002,04 4F,43 4F,1E 4F,1E 4F,7C 51,7D 51,7E " +
        "51,7B 53,43 53,7B 55,43 55,7B 57,7B 59,7B 59,1E 5C,43 5C,43 5E,1E 5E,20 60,7B 62,43 62,7B 64,20 " +
        "64,52 64,52 64,7C 64,7C 66,43 66,43 69,7B 6B,87 6B,87 6B,7C 6B,7F 6D,57 6D,43 6D,43 6D,59 6F,52 " +
        "6F,52 6F,7B 71,7B 76,43 76,43 78,1E 78,1E 7902 7902,7C 7902,7C 7902,7D 3A,03 4102,03 4102,03 790A 73,7B " +
        // U+01C4..U+01CC are the DŽ/LJ/NJ ligature characters. Each is TWO weights, not one, and the second
        // may carry its own accent — ACE stores Ǆ as 7F 4F 78 01 02 14 00, i.e. D then Ž. A single block
        // entry cannot express that, so they are refused rather than encoded as one weight, which would be
        // silently wrong in any string where a later character is accented.
        "330B 330C 330D 2B17 ? ? ? ? ? ? ? ? ? 4A,14 4A,14 59,14 " +
        "59,14 64,14 64,14 6F,14 6F,14 6F,28 6F,28 6F,1F 6F,1F 6F,25 6F,25 6F,20 6F,20 51,7D 4A,28 4A,28 " +
        // U+01E2/E3 (Ǣ, AE with macron) is an accented expansion — two weights each carrying the accent —
        // and the letters it expands to are locale-dependent: Icelandic gives it its own Æ, 79 04, with a
        // different secondary again. Refused rather than guessed, like the ligatures above.
        "4A,25 4A,25 ? ? 55,1E 55,1E 55,14 55,14 5C,14 5C,14 64,1B 64,1B 64,30 64,30 7902,14 7902,14 " +
        "5B,14 ? ? ? 55,0E 55,0E - - - - 4A,26 4A,26 ? ? 64,2B 64,2B " +
        "4A,44 4A,44 4A,46 4A,46 51,44 51,44 51,46 51,46 59,44 59,44 59,46 59,46 64,44 64,44 64,46 64,46 " +
        "69,44 69,44 69,46 69,46 6F,44 6F,44 6F,46 6F,46 - - - - - - - - " +
        "- - - - - - - - - - - - - - - - " +
        "- - - - - - - - - - - - - - - - " +
        "- - - - - - - - - - - - - - - - ",

        // Spacing modifiers — U+02B0..U+02FF
        "02B0|" +
        "57,7E 57,7F 5B,7E 69,81 69,82 69,83 69,84 73,7E 76,7E ,0C ,19 ,45 ,46 ,47 ,77 ,78 " +
        ",3F ,79 ,7A ,7B ,7C ,7D 2B02,03 2B18 ,40 2B13,03 2B14,03 2B07,03 ,5A ,62 ,7E ,7F " +
        "2B99 ,81 ,82 ,83 ,50 ,51 ,52 ,53 2B18,03 2B19 2B1A 2B1B 2B1C 2B1D ,84 - " +
        "55,7E 5E,7E 6B,7E 75,7E ,85 ,86 ,87 ,88 ,89 ,8A - - - - - - " +
        "- - - - - - - - - - - - - - - - ",

        // Greek — U+0370..U+03FF
        "0370|" +
        ",91 ,92 ,93 - 2B1E 2B1F - - - - 2B20 - - - 2B21 - " +
        "- - - - 2B22 2B23 790C,05 - 7910,05 7912,05 7914,05 - 791A,05 - 791F,05 7923,05 " +
        "7914,16 790C 790D 790E 790F 7910 7911 7912 7913 7914 7915 7916 7917 7918 7919 791A " +
        "791B 791C - 791D 791E 791F 7920 7921 7922 7923 7914,13 791F,13 790C,05 7910,05 7912,05 7914,05 " +
        "791F,16 790C 790D 790E 790F 7910 7911 7912 7913 7914 7915 7916 7917 7918 7919 791A " +
        "791B 791C 791D 791D 791E 791F 7920 7921 7922 7923 7914,13 791F,13 791A,05 791F,05 7923,05 - " +
        "790D,03 7913,03 791F,1B 791F,44 791F,13 7920,03 791B,03 - - - 7924 7924 7925 7925 7926 7926 " +
        "7927 7927 7928 7928 7929 7929 792A 792A 792B 792B 792C 792C 792D 792D 792E 792E " +
        "7915,03 791C,03 791D,04 - - - - - - - - - - - - - ",

        // Cyrillic — U+0400..U+04FF
        "0400|" +
        "- 7936,13 7935 7932,0E 7937 793A 793C 793D 793F 7942 7945 794B 7940,0E - 794E 7954 " +
        "792F 7930 7931 7932 7933 7936 7938 7939 793B 793E 7940 7941 7943 7944 7946 7947 " +
        "7948 7949 794A 794D 7950 7951 7952 7953 7955 7956 7957 7958 7959 795A 795B 795C " +
        "792F 7930 7931 7932 7933 7936 7938 7939 793B 793E 7940 7941 7943 7944 7946 7947 " +
        "7948 7949 794A 794D 7950 7951 7952 7953 7955 7956 7957 7958 7959 795A 795B 795C " +
        "- 7936,13 7935 7932,0E 7937 793A 793C 793D 793F 7942 7945 794B 7940,0E - 794E 7954 " +
        "795E 795E 795F 7944,03 7960 7960 7961 7961 7962 7962 7963 7963 7964 7964 7965 7965 " +
        "7966 7966 7967 7967 7968 7968 7968,46 7968,46 7969 7969 796A 796A 796B 796B 796C 796C " +
        "796D 796D 4926,37 ,94 ,95 ,96 ,97 - - - - - - - - - " +
        "7932,03 7932,03 7932,1A 7932,1A 7932,05 7932,05 7938,07 7938,07 7939,1A 7939,1A 7940,17 7940,17 7940,09 7940,09 7940,04 7940,04 " +
        "7940,0A 7940,0A 7944,07 7944,07 7944,08 7944,08 7947,05 7947,05 7946,05 7946,05 7949,1A 7949,1A 794A,07 794A,07 794D,0B 794D,0B " +
        "794F 794F 7951,17 7951,17 7952,03 7952,03 7953,08 7953,07 7953,09 7953,09 7944,09 7944,09 7936,05 7936,05 7936,17 7936,17 " +
        "793C,03 7938,15 7938,15 7940,05 7940,05 7940,06 7940,06 7944,0A 7944,0A 7951,06 7951,06 7953,0D 7953,0D - - - " +
        "- - - - - - - - - - - - - - - - " +
        "- - - - - - - - - - - - - - - - " +
        "- - - - - - - - - - - - - - - - ",

        // Cyrillic Supplement — U+0500..U+052F: present in the file format, but ACE weighs none of it.
        "0500|" +
        "- - - - - - - - - - - - - - - - " +
        "- - - - - - - - - - - - - - - - " +
        "- - - - - - - - - - - - - - - - ",

        // Hebrew — U+0590..U+05FF
        "0590|" +
        "- ,03 ,04 ,05 ,06 ,07 ,08 ,09 ,0A ,0B ,0C ,0D ,0E ,0F ,10 ,11 " +
        ",12 ,13 ,14 ,15 ,16 ,17 ,18 ,19 ,1A ,1B ,1C ,1D ,1E ,1F ,20 ,21 " +
        ",22 ,23 ,24 ,25 ,26 ,27 ,28 ,29 ,2A ,2B ,2C ,2D ,2E ,2F 2B2A ,30 " +
        ",31 ,32 ,33 2B2B - - - - - - - - - - - - " +
        "7994 7995 7996 7997 7998 7999 799A 799B 799C 799D 799E 799E 799F 79A0 79A0 79A1 " +
        "79A1 79A2 79A3 79A4 79A4 79A5 79A5 79A6 79A7 79A8 79A9 - - - - - " +
        "79997999 7999799D 799D799D 2B2C 2B2D - - - - - - - - - - - ",

        // Arabic — U+0600..U+06FF
        "0600|" +
        "- - - - - - - - - - - - 2B2E - - - " +
        "- - - - - - - - - - - 2B2F - - - 2B30 " +
        "- 79AA 79AA,03 79AA,04 79AA,05 79AA,06 79AA,07 79AB,08 79AC,08 79AE,08 79AE,08 79AF,08 79B0,08 79B2,08 79B3,08 79B4,08 " +
        "79B5,08 79B6,08 79B7,08 79B9,08 79BA,08 79BB,08 79BC,08 79BD,08 79BE,08 79BF,08 79C0,08 - - - - - " +
        "- 79C1,08 79C2,08 79C3,08 79C5,08 79C6,08 79C7,08 79C8,08 79C9,08 79CA,05 79CA,07 ? ? ? ? ? " +
        "? FFFF ? - - - - - - - - - - - - - " +
        "3702,38 3902,38 3B02,38 3D02,38 3F02,38 4103,38 4302,38 4502,38 4702,38 4902,38 2B31 2B32 2B33 - - - " +
        "79CB 79CC 79CD 79CE 79CF 79D0 79D1 79D2 79D3 79D4 79D5 79D6 79D7 79D8 79AD,08 79D9 " +
        "79DA 79DB 79DC 79DD 79DE 79DF 79B1,08 79E0 79E1 79E2 79E3 79E4 79E5 79E6 79E7 79E8 " +
        "79E9 79EA 79EB 79EC 79ED 79EE 79EF 79F0 79B8,08 79F1 79F2 79F3 79F4 79F5 79F6 79F7 " +
        "79F8 79F9 79FA 79FB 79FC 79FD 79FE 79FF 7A02 7A03 7A04 7A05 7A06 7A07 7A08 79C4,08 " +
        "7A09 7A0A 7A0B 7A0C 7A0D 7A0E 7A0F 7A10 7A11 7A12 7A13 7A14 7A15 7A16 7A17 7A18 " +
        "7A19 7A1A 7A1B 7A1C 7A1D 7A1E 7A1F 7A20 7A21 7A22 7A23 7A24 7A25 7A26 7A27 7A28 " +
        "7A29 7A2A 7A2B 7A2C 2B34 7A2D - - - - - - - - - - " +
        "- - - - - - - - - - - - - - - - " +
        "3703,39 3903,39 3B03,39 3D03,39 3F03,39 4104,39 4303,39 4503,39 4703,39 4903,39 - - - - - - ",

        // Latin Extended Additional — U+1E00..U+1EFF (the Vietnamese precomposed letters live here)
        "1E00|" +
        "4A,5A 4A,5A 4C,10 4C,10 4C,58 4C,58 4C,55 4C,55 4D,28 4D,28 4F,10 4F,10 4F,58 4F,58 4F,55 4F,55 " +
        "4F,1C 4F,1C 4F,60 4F,60 51,24 51,24 51,23 51,23 51,60 51,60 51,63 51,63 51,2F 51,2F 53,10 53,10 " +
        "55,17 55,17 57,10 57,10 57,58 57,58 57,13 57,13 57,1C 57,1C 57,61 57,61 59,63 59,63 59,1F 59,1F " +
        "5C,0E 5C,0E 5C,58 5C,58 5C,55 5C,55 5E,58 5E,58 5E,6E 5E,6E 5E,55 5E,55 5E,60 5E,60 60,0E 60,0E " +
        "60,10 60,10 60,58 60,58 62,10 62,10 62,58 62,58 62,55 62,55 62,60 62,60 64,25 64,25 64,2A 64,2A " +
        "64,24 64,24 64,23 64,23 66,0E 66,0E 66,10 66,10 69,10 69,10 69,58 69,58 69,6E 69,6E 69,55 69,55 " +
        "6B,10 6B,10 6B,58 6B,58 6B,1D 6B,1D 6B,22 6B,22 6B,68 6B,68 6D,10 6D,10 6D,58 6D,58 6D,55 6D,55 " +
        "6D,60 6D,60 6F,59 6F,59 6F,63 6F,63 6F,5A 6F,5A 6F,25 6F,25 6F,28 6F,28 71,19 71,19 71,58 71,58 " +
        "73,0F 73,0F 73,0E 73,0E 73,13 73,13 73,10 73,10 73,58 73,58 75,10 75,10 75,13 75,13 76,10 76,10 " +
        "78,12 78,12 78,58 78,58 78,55 78,55 57,55 6D,13 73,1A 76,1A 4A,69 - - - - - " +
        "4A,59 4A,59 4A,43 4A,43 4A,1E 4A,1E 4A,1F 4A,1F 4A,55 4A,55 4A,29 4A,29 4A,6A 4A,6A 4A,21 4A,21 " +
        "4A,22 4A,22 4A,58 4A,58 4A,2C 4A,2C 4A,6D 4A,6D 51,58 51,58 51,43 51,43 51,19 51,19 51,1E 51,1E " +
        "51,1F 51,1F 51,55 51,55 51,29 51,29 51,6A 51,6A 59,43 59,43 59,58 59,58 64,58 64,58 64,43 64,43 " +
        "64,1E 64,1E 64,1F 64,1F 64,55 64,55 64,29 64,29 64,6A 64,6A 64,60 64,60 64,61 64,61 64,95 64,95 " +
        "64,69 64,69 64,AA 64,AA 6F,58 6F,58 6F,43 6F,43 6F,60 6F,60 6F,61 6F,61 6F,95 6F,95 6F,69 6F,69 " +
        "6F,AA 6F,AA 76,0F 76,0F 76,58 76,58 76,44 76,44 76,19 76,19 - - - - - - ",

        // General punctuation — U+2000..U+206F
        "2000|" +
        "0808 0809 080A 080B 080C 080D 080E 080F 0810 0811 0812 0813 0814 - - - " +
        "? ? ? ? ? ? 2B35 2B36 2B37 2B38 2B39 2B3A 2B3B 2B3C 2B3D 2B3E " +
        "34B3 34B4 34B5 34B6 34B7 34B8 34B9 ? 0815 0816 - - - - - - " +
        "34BA 34BB 2B3F 2B40 2B41 2B42 2B43 2B44 2B45 2B46 2B47 34BC 2B48 2B49 2B4A 2B4B " +
        "34BD 34BE 34BF ? 2D05 27,1C 2A,1C - - - - - - - - - " +
        "- - - - - - - - - - - - - - - - " +
        "- - - - - - - - - - - - - - - - ",

        // Currency — U+20A0..U+20BF
        "20A0|" +
        "34C0 34C1 34C2 34C3 34C4 34C5 34C6 34C7 34C8 34C9 34CA 34CB 35A1 - - - " +
        "- - - - - - - - - - - - - - - - ",

        // Letterlike — U+2100..U+214F
        "2100|" +
        "4B04 4B06 4D,03 4D,04 4E0A 4E0F 4E10 51,64 6C02 53,04 55,03 57,05 57,04 57,03 57,03 57,68 " +
        "59,04 59,05 5E,04 5E,04 5F02 62,03 6302 35A0 66,04 66,03 68,03 69,04 69,05 69,03 6A02 6A03 " +
        "6C03 6E02 6E04 7202 78,03 78,63 7923,03 7923,05 78,05 7923,04 5D02 4A,1A 4C,04 4D,05 51,05 51,04 " +
        "51,04 53,05 53,03 60,04 64,04 7994 7995 7996 7997 - - - - - - - " +
        "- - - - - - - - - - - - - - - - ",

        // Number forms — U+2150..U+218F
        "2150|" +
        "- - - 3713 3719 3711 3715 3717 371B 3710 371C 370F 3714 3718 371D 38,03 " +
        "3910,47 3B10,47 3D10,47 3F10,47 4111,47 4310,47 4510,47 4710,47 4910,47 4914,47 4916,47 4918,47 4922,47 4924,47 4925,47 4928,47 " +
        "3910,47 3B10,47 3D10,47 3F10,47 4111,47 4310,47 4510,47 4710,47 4910,47 4914,47 4916,47 4918,47 4922,47 4924,47 4925,47 4929,47 " +
        "492A,47 492B,47 492C,47 - - - - - - - - - - - - - ",

        // Fullwidth forms — U+FF01..U+FF65. They repeat the ASCII weights exactly, which is the width folding
        // described in §10.4 falling out of the table rather than being a normalisation pass.
        "FF01|" +
        "09 0A 0C 0E 10 12 ? 14 16 18 2C 1A ? 1C 1E 36 " +
        "38 3A 3C 3E 40 42 44 46 48 20 22 2E 30 32 24 26 " +
        "4A 4C 4D 4F 51 53 55 57 59 5B 5C 5E 60 62 64 66 " +
        "68 69 6B 6D 6F 71 73 75 76 78 27 29 2A 2B02 2B03 2B07 " +
        "4A 4C 4D 4F 51 53 55 57 59 5B 5C 5E 60 62 64 66 " +
        "68 69 6B 6D 6F 71 73 75 76 78 2B09 2B0B 2B0D 2B0F - - " +
        "1D02 2B59 2B5B 1B03 34B2 ",
    ];
}
